name: Feature
description: Add or improve functionality
title: "feat: "
labels:
  - feature

body:
  - type: input
    id: issue_number
    attributes:
      label: Issue number
      description: The GitHub issue number (e.g. 2)
      placeholder: "2"
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should be built?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Checklist of requirements
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Files or areas affected

  - type: textarea
    id: testing
    attributes:
      label: How to Test

  - type: markdown
    attributes:
      value: |
        ### Implementation Guidance
        - Keep changes incremental.
        - Maintain a working application state throughout implementation.
        - If implementation becomes large, complete the work in logical stages rather than one large change.