name: Feature
description: Add or improve functionality
title: "feat: "
labels:
  - feature

body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should be built?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Checklist of requirements
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Files or areas affected

  - type: textarea
    id: testing
    attributes:
      label: How to Test